version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: ./docker_compose.yml
    image: jobvacdockerimage
    ports:
      - 8095:80
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - facilitymanagementportal
  mysql:
    image: library/mysql:8.0.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 5306:3306
    environment:
      MYSQL_DATABASE: facilityManagement
      MYSQL_USER: root
      MYSQL_PASSWORD: 7siIYw6bdFcaBnRw
      MYSQL_ROOT_PASSWORD: 7siIYw6bdFcaBnRw
    networks:
      - facilitymanagementportal
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8005:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 7siIYw6bdFcaBnRw
    networks:
      - facilitymanagementportal
networks:
  facilitymanagementportal:
volumes:
  db_data:
